### ISSUE TITLE
Roadmap for v0.3

### ISSUE THREAD

**Issue by burodepeper** [burodepeper/language-markdown#39]
- Thin out the specs:
  - [x] Remove unneccessary repeated elements that provide context unimportant to syntax highlighting
  - [x] Remove duplicates
  - [x] Remove tests aimed at interpretation rather than representation (for instance, uppercase vs lowercase testing, or logical dependencies)
- [x] Support advanced gfm references (#35)
- [x] Add support for TOML front matter (#36)
- Add Markdown Extra flavor (#37)
  - [x] Add special attributes ({}) to headings, fenced code blocks, links and images
  - [x] Defintion lists
  - [x] Footnotes
  - [x] Abbreviations
  - [x] Add specs and examples for Markdown Extra
- ~~language-gfm/issues/40~~
- [x] Update README (include screenshots, Markdown Extra)
