### ISSUE TITLE
Improve compatibility with default syntax-themes (work in progress)

### ISSUE THREAD

**Issue by burodepeper** [burodepeper/language-markdown#52]
Current progress of this issue is tracked in PR #83. All information below is retained as a backup.

---

Most markup related styles (primarily used for Markdown purposes incidently) in syntax themes are directly linked to the `gfm` scope of the `language-gfm` package. Instead, the more convenient `markup` scope should be used for styling generic markup. To improve the compatibility with this package (and any other markup related packages) PRs fixing these scopes need to be submitted for all default syntax themes. Somebody has to do it, right?

I am using this issue to track the progress of these connected PRs. The document used to check supported styles is [DIVERSITY.md](https://raw.githubusercontent.com/burodepeper/language-markdown/dev/DIVERSITY.md) on the dev branch.

#### todo
- [ ] Change the default source from which syntax-themes are created
- [ ] Create a drop-in `markdown.less` file with mappable variables to quickly support syntax-themes.

#### atom-dark-syntax
- [ ] headings
- [ ] italics
- [ ] inline-code
- [x] fenced-code
- [ ] links (label + link) + images
- [ ] link-reference
- [ ] horizontal-rule
- [ ] list-items (ordered, unordered, task)
- [ ] quote
- [ ] bold (strong emphasis)
- [ ] auto-links
- [ ] strike-through
- [ ] criticmark (except comments)
- [ ] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [x] tables
- [ ] escaped characters
- [ ] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### atom-light-syntax
- [ ] headings
- [ ] italics
- [ ] inline-code
- [x] fenced-code
- [ ] links (label + link) + images
- [ ] link-reference
- [ ] horizontal-rule
- [ ] list-items (ordered, unordered, task)
- [ ] quote
- [ ] bold (strong emphasis)
- [ ] auto-links
- [ ] strike-through
- [ ] criticmark (except comments)
- [ ] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [x] tables
- [ ] escaped characters
- [ ] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### base16-tomorrow-dark-theme
- [ ] headings
- [x] italics
- [x] inline-code
- [x] fenced-code
- [ ] links (label + link) + images
- [ ] link-reference
- [ ] horizontal-rule
- [x] list-items (ordered, unordered, task)
- [x] quote
- [x] bold (strong emphasis)
- [ ] auto-links
- [ ] strike-through
- [x] criticmark (except comments)
- [x] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [x] tables
- [x] escaped characters
- [ ] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### base16-tomorrow-light-theme
- [ ] headings
- [x] italics
- [x] inline-code
- [x] fenced-code
- [ ] links (label + link) + images
- [ ] link-reference
- [ ] horizontal-rule
- [x] list-items (ordered, unordered, task)
- [x] quote
- [x] bold (strong emphasis)
- [ ] auto-links
- [ ] strike-through
- [x] criticmark (except comments)
- [x] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [x] tables
- [x] escaped characters
- [x] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### one-dark-syntax
- [x] headings
- [x] italics
- [x] inline-code
- [x] fenced-code
- [x] links (label + link) + images
- [x] link-reference
- [ ] horizontal-rule
- [ ] list-items (ordered, unordered, task)
- [x] quote
- [x] bold (strong emphasis)
- [x] auto-links
- [x] strike-through
- [x] criticmark (except comments)
- [x] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [x] tables
- [x] escaped characters
- [x] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### one-light-syntax
- [ ] headings
- [x] italics
- [x] inline-code
- [x] fenced-code
- [ ] links (label + link) + images
- [ ] link-reference
- [ ] horizontal-rule
- [x] list-items (ordered, unordered, task)
- [x] quote
- [x] bold (strong emphasis)
- [ ] auto-links
- [ ] strike-through
- [x] criticmark (except comments)
- [x] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [x] tables
- [x] escaped characters
- [x] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### solarized-dark-syntax
- [x] headings
- [x] italics
- [ ] inline-code
- [x] fenced-code
- [x] links (label + link) + images
- [x] link-reference
- [ ] horizontal-rule
- [ ] list-items (ordered, unordered, task)
- [ ] quote
- [x] bold (strong emphasis)
- [x] auto-links
- [ ] strike-through
- [ ] criticmark (except comments)
- [ ] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [ ] tables
- [x] escaped characters
- [x] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

#### solarized-light-syntax
- [x] headings
- [x] italics
- [ ] inline-code
- [x] fenced-code
- [x] links (label + link) + images
- [x] link-reference
- [ ] horizontal-rule
- [ ] list-items (ordered, unordered, task)
- [ ] quote
- [x] bold (strong emphasis)
- [x] auto-links
- [ ] strike-through
- [ ] criticmark (except comments)
- [ ] class, id and key=value in special-attributes
- [x] inline html, css and javascript
- [x] gfm references
- [x] emojis
- [ ] tables
- [x] escaped characters
- [x] nested inline styles
- [x] front-matter
- [x] entities
- [x] comments

**Comment by jmgore75** [comment]
FYI the one-dark-syntax (1.1.1) notes don't match what I see: 

- Headings not highlighted
- hyperlinks not highlighted, either in braces or out
- tables without outer pipes are not highlighted

![image](https://cloud.githubusercontent.com/assets/5373543/12432980/66572f8c-becc-11e5-9a7f-8554876fed56.png)

**Comment by burodepeper** [comment]
@jmgore75 Thanks for reporting/verifying. I have yet to come up with a better way to provide support for syntax-themes. It's proven to be quite a chore. :frowning:

The tables without an outer pipe not highlighting is intentionally. Enabling it caused too many false-positives in my opinion. However, I might add the feature as an option in a feature version, where you are able to select which elements/flavors you want enabled.

**Comment by burodepeper** [comment]
See #83 for current status

**Comment by polarathene** [comment]
So for any theme to support markdown syntax properly with l`anguage-gfm` enabled will need to be reworked for `language-markdown`? I've gone into settings and unchecked the `disable language-gfm` setting (still had to re-enable `language-gfm`), but the syntax theme is not adjusted accordingly even when restarting Atom. Is something else breaking the syntax theme? 

I like `language-markdown` features but also find partially themed syntax being applied a bit frustrating. This is a fresh install of Atom, haven't applied my preferred themes yet, I assume based on this issue that without any support the syntax theme will not show applied at all.

**Comment by burodepeper** [comment]
Yes and no. At the moment it is a bit of a trade off, but I'm working on a better solution. The main issue is that there are no set rules for syntax-themes, and neither are there for grammar-packages. When I started this package, I implemented a whole bunch of extra functionality, but I sort of forgot to see how it worked with existing themes because I work on [minimal-syntax](/burodepeper/minimal-syntax) and [minimal-syntax-dark](/burodepeper/minimal-syntax) in tandem.

When I looked into supporting the default themes I noticed that some default classes to style markup elements had all been scoped exclusively to the `gfm` package (in a sense). In cooperation with @simurai (from the Atom team) I've suggested some changes to these default themes, but that still leaves a bunch of stuff partially themed, or sometimes not at all.

I'm a currently (see #83) working on a way to map a theme's syntax-color-variables to any markup/markdown classes. This is something that syntax-themes can use. I'm also in the progress of changing the default scope of the grammar to use standard classes defined as `source`. It's quite a big overhaul of the entire package, so it might take a little while until you'll have fully themed markdown files.

In the mean time, you can use the two themes I mentioned earlier as they implement all functionality this package has to offer. #83 will take a lot of testing to get it right, but when that's done, I reckon every syntax-theme will work (at least acceptably) with this package out of the box.

@polarathene I am not sure about your particular issue with the syntax-theme not working, but I believe by default Atom selects a custom grammar over one that's bundled. So re-enabling `language-gfm` still has you using `language-markdown`. In the bottom right hand corner, there's a label that says which grammar you are using. Make sure this is the gfm package if you want to use it. I think I'll bump the version to v1.0.0 when I've finished #83, so if you disable `language-markdown` until then, you know when it is safe to use again ; ) If you still run into any issues, feel free to report them here and I'll see what I can do.

**Comment by polarathene** [comment]
@burodepeper Thanks for that, changing from `Markdown` to `Github Markdown` was what I was after :) I look forward to #83 being completed! Thanks for all the work you've put into this package. The only other feature I'd love to see for Markdown in Atom would be increasing the font size for headers like in some other Markdown editors, though I think I've read of Atom devs finding that difficult to get working well.

**Comment by burodepeper** [comment]
@polarathene You're welcome. And changing the font-size for headers is indeed an issue. The line-height is assumed to be the same for every line. That makes positioning decorations (such as search results) convenient. Having variable line-heights makes stuff like that rather tedious, so I get where they're coming from. Having said that, it also goes against the idea of Markdown, doesn't it? :p It is intended to be readable as plain text. I feel the same way though; at some point headers simply don't stand out as much anymore.

**Comment by burodepeper** [comment]
I'm abandoning this for now. After careful consideration the investment is simply too big, and I'm hoping for better scope-name standards in a future Atom 2.
